import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./provider";
import Navbar from "@/components/Navbar";
import useInfoModalStore from "@/hooks/useInfoModalStore";
import InfoModal from "@/components/InfoModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const { isOpen, closeModal } = useInfoModalStore();

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
        <InfoModal visible={isOpen} onClose={closeModal} />

          <Navbar />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
